version = 0.1

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name = "web-python-fastapi-dev"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
s3_prefix = "web-python-fastapi-dev"
parameter_overrides = "Stage=dev DomainName= DomainCertificateArn="
tags = "Project=web-python-fastapi Environment=dev ManagedBy=sam"

[prod.deploy.parameters]
stack_name = "web-python-fastapi-prod"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "web-python-fastapi-prod"
parameter_overrides = "Stage=prod DomainName= DomainCertificateArn="
tags = "Project=web-python-fastapi Environment=prod ManagedBy=sam"
