name: Git-flow

on:
  pull_request:
    branches: ["main", "master", "develop"]

jobs:
  gitflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actionplatform/ci-github/gitflow@v1
